version: "3.7"
services:
  docker-spring-security-mysql-mvc-prod:
    image: imranmadbar/docker-spring-security-mysql-mvc-prod:3.0.0.RELEASE
    container_name: docker-spring-security-mysql-mvc-prod
    ports:
      - "8181:8181"
    links:
        - "mysql-dkr-contr-db:mysql-dkr-contr-db"
    depends_on:
      - mysql-dkr-contr-db
  mysql-dkr-contr-db:
    image: mysql:5.7
    container_name: mysql-dkr-contr-db
    volumes:
      - db-data:/var/lib/mysql 
    ports:
      - "3306:3306"
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: imranmabar_spring_security_db
      
volumes:
    db-data:
        driver: local